#python predict_test.py --path_save predictions --model_checkpoint SMSC_train_stripped_swin_seed1/model_epoch_66.pth --input_val_paths ../SMSC_Basel_stripped/test_selected ../SMSC_Basel_stripped/test_selected --target_val_path ../SMSC_Basel_stripped/test_selected --target_prefix lesion_mask_final.nii.gz --input_prefixes flair_brain.nii.gz t1n_brain.nii.gz --num_workers 6 --cache_rate 0.1 --model swin_unetr --seed 1 --batch_size 1 --eval_set_name test
import os
import pandas as pd
from joblib import Parallel, delayed
from functools import partial
from scipy import ndimage
import nibabel as nib
# random seed fix
import numpy as np
import matplotlib.pyplot as plt
import numpy as np
import scipy.stats as stats

def intersection_over_union(mask1, mask2):
    """Compute IoU for 2 binary masks
    mask1 and mask2 should have same dimensions
    """
    return np.sum(mask1 * mask2) / np.sum(mask1 + mask2 - mask1 * mask2)

def entropy_of_expected(probs, epsilon=1e-10):
    """
    :param probs: array [num_models, num_voxels_X, num_voxels_Y, num_voxels_Z, num_classes]
    :return: array [num_voxels_X, num_voxels_Y, num_voxels_Z,]
    """
    mean_probs = np.mean(probs, axis=0)
    log_probs = -np.log(mean_probs + epsilon)
    return np.sum(mean_probs * log_probs, axis=-1)

def lesion_structural_uncertainty(cc_mask: np.ndarray, ens_pred_multi: np.ndarray):
    """ Compute lesion structural uncertainty for a single connected component.
    :param cc_mask: binary lesion mask, shape [H, W, D]
    :param ens_pred_multi: labeled lesions masks generated by an ensemble of models, shape [M, H, W, D].
    :return: uncertainty value (float)
    """
    def get_max_ious_ccmasks_ens(ens_multi):
        ens_ious_ = []
        for m in range(ens_multi.shape[0]):
            max_iou = 0.0
            for intersec_label in np.unique(cc_mask * ens_multi[m]):
                if intersec_label != 0.0:
                    lesion_m = (ens_multi[m] == intersec_label).astype(float)
                    iou = intersection_over_union(cc_mask, lesion_m)
                    if iou > max_iou:
                        max_iou = iou
            ens_ious_.append(max_iou)
        return ens_ious_

    # lesion structural uncertainty measure
    # 1 - mean IoU of connected components on the ensemble's models prediction with cc_mask
    ens_ious = get_max_ious_ccmasks_ens(ens_pred_multi)
        
    return  1 - np.mean(ens_ious)


def lesion_structural_uncertainty_full(cc_mask: np.ndarray, vox_uncs_map: np.ndarray, ens_pred_multi: np.ndarray,
                                  ens_pred_prob: np.ndarray, epsilon: float = 1e-5):
    """ Compute different uncertainty measures for a single connected component, that include:
    * Mean from vox uncertainty (M Dojat)
    * Log-sum from vox uncertainty (T Alber)
    * Ensemble detection uncertainty (ours)
    * Andrey's proposal: RMI avg_prod and prod_avg, MI (avg_prod and prod_avg) x (same threshold and unique thresholds)
    on the structural scale
    :param cc_mask: binary lesion mask, shape [H, W, D]
    :param vox_uncs_map: voxel scale uncertainty map, shape [H, W, D]
    :param ens_pred_multi: labeled lesions masks generated by an ensemble of models - threshold tuned for ensemble, shape [M, H, W, D].
    :param ens_pred_prob: probabilities predicted by each model in ensemble
    :param epsilon: small value to avoid -inf in logarithms
    :return: dictionary of lesion uncertainty measures
    :rtype: dict
    """
    def get_max_ious_ccmasks_ens(ens_multi):
        ens_ious_ = []
        for m in range(ens_multi.shape[0]):
            max_iou = 0.0
            for intersec_label in np.unique(cc_mask * ens_multi[m]):
                if intersec_label != 0.0:
                    lesion_m = (ens_multi[m] == intersec_label).astype(float)
                    iou = intersection_over_union(cc_mask, lesion_m)
                    if iou > max_iou:
                        max_iou = iou
            ens_ious_.append(max_iou)
        return ens_ious_

    # check inputs
    if not cc_mask.shape == vox_uncs_map.shape == ens_pred_multi[0].shape == ens_pred_prob[0].shape:
        raise ValueError("Error in input dimensions:\n"
                         f"cc_mask: {cc_mask.shape}, "
                         f"vox_uncs_map: {vox_uncs_map.shape}, "
                         f"ens_pred_prob: {ens_pred_prob.shape}, "
                         f"ens_pred_multi: {ens_pred_multi.shape}.")
    if not ens_pred_prob.shape == ens_pred_multi.shape:
        raise ValueError("Expecting same number of models in the ensemble:\n"
                         f"ens_pred_prob: {ens_pred_prob.shape}, "
                         f"ens_pred_multi: {ens_pred_multi.shape}.")

    # lesion structural uncertainty measure
    # 1 - mean IoU of connected components on the ensemble's models prediction with cc_mask
    ens_ious = get_max_ious_ccmasks_ens(ens_pred_multi)
        
    return  1 - np.mean(ens_ious)

def lesion_uncertainty_maps(pred_filepath: str, affine: np.ndarray, save_path: str, num_models: int = 5, n_jobs: int = 1):
    """Compute lesion uncertainty map (LSU measure) and save it.

    Args:
        pred_filepath (str): npz prediction file path (produced by prediction.py)
        affine (np.ndarray): affine transformation matrix from nifti file
        save_path (str): path to save the uncertainty map
        num_models (int, optional): number of models in the ensemble. Defaults to 5.
        n_jobs (int, optional): number of jobs for parallel processing. Defaults to 1.

    Raises:
        ValueError: if prediction mask is not empty, but no lesions found for uncertainty computation.

    Returns:
        _type_: None
    """
    # load prediction npz file
    pred = np.load(pred_filepath)
    
    # return empty mask if no lesions were predicted
    if pred['ens_seg'].sum() == 0:
        return np.zeros_like(pred['ens_seg'])
     
    # determine individual connected components on the prediction of the ensemble
    struct_el = ndimage.generate_binary_structure(rank=3, connectivity=2)
    les_mask_multi = ndimage.label(
        pred['ens_seg']
        , structure=struct_el
        )[0]
    
    # determine individual connected components on the predictions of each ensemble member (num_models, H, W, D) 
    ens_pred_multi = np.stack([
        ndimage.label(pred['seed%d_seg_true' % i])[0] for i in range(1, num_models + 1)
    ])
    
    cc_labels = np.unique(les_mask_multi)
    cc_labels = cc_labels[cc_labels != 0.0]
    
    # parallel computation of lesion structural uncertainty measures for each connected component
    with Parallel(n_jobs=n_jobs) as parallel_backend:
        process = partial(lesion_structural_uncertainty, ens_pred_multi=ens_pred_multi)
        
        # returns lists of float values, each corresponding to a connected component
        les_uncs_list = parallel_backend(delayed(process)(
            cc_mask=(les_mask_multi == cc_label).astype("float")
        ) for cc_label in cc_labels)

    # create a mask in case uncertainty was computed
    if les_uncs_list:
        les_uncs_mask = np.zeros_like(les_mask_multi, dtype='float32')
        for cc_label, les_uncs_value in zip(cc_labels, les_uncs_list):
            les_uncs_mask += les_uncs_value * (les_mask_multi == cc_label).astype('float')
    else:
        raise ValueError("Prediction is not empty, but no lesions found for uncertainty computation.")

    # save uncertainty map
    nib.Nifti1Image(les_uncs_mask, affine=affine).to_filename(save_path)

def voxel_uncertainty_maps(pred_filepath: str, affine: np.ndarray, save_path: str, num_models: int = 5, n_jobs: int = 1):
    """Compute voxel uncertainty map (EoE measure) and save it.

    Args:
        pred_filepath (str): npz prediction file path (produced by prediction.py)
        affine (np.ndarray): affine transformation matrix from nifti file
        save_path (str): path to save the uncertainty map
        num_models (int, optional): number of models in the ensemble. Defaults to 5.
        n_jobs (int, optional): number of jobs for parallel processing. Defaults to 1.

    Returns:
        _type_: None
    """
    # load prediction npz file
    pred = np.load(pred_filepath)
     
    # probability predictions of each ensemble member (num_models, H, W, D)
    ens_pred = np.stack([pred['seed%d_prob' % i] for i in range(1, num_models + 1)], axis=0)

    vox_uncs_maps = entropy_of_expected(np.concatenate(
        (np.expand_dims(ens_pred, axis=-1),
            np.expand_dims(1. - ens_pred, axis=-1)),
        axis=-1))
    
    # save uncertainty map
    nib.Nifti1Image(vox_uncs_maps.astype('float32'), affine=affine).to_filename(save_path)
    
def patient_uncertainty_value(pred_filepath: str, num_models: int = 5):
    
    """Compute patient uncertainty value (PSU) and return it.

    Args:
        pred_filepath (str): npz prediction file path (produced by prediction.py)
        num_models (int, optional): number of models in the ensemble. Defaults to 5.
    
    Returns:
        float: patient uncertainty value, None if no lesions were predicted
    """
    # load prediction npz file
    pred = np.load(pred_filepath)
    
    # return empty mask if no lesions were predicted
    if pred['ens_seg'].sum() == 0:
        return None
    
    # patient uncertainty value
    psu = 1 - np.mean([intersection_over_union(pred['ens_seg'], pred['seed%d_seg_true' % i]) for i in range(1, num_models + 1)])
    
    return psu

def plot_psu_distribution(psu_data: np.ndarray, new_psu_value: float, save_path: str, x_min=0, x_max=1):
    """Plot the new patient uncertainty value (PSU) wrt PSU distribution.

    Args:
        psu_data (np.ndarray): an array of PSU value from the test population
        new_psu_value (float): the new PSU value to plot
        save_path (str): path to save the plot
        x_min (int, optional): minimum x-axis value. Defaults to 0.
        x_max (int, optional): maximum x-axis value. Defaults to 1.
    """
    # Estimate PDF using kernel density estimation
    kde = stats.gaussian_kde(psu_data)

    # Create a range for plotting
    if x_min is None or x_max is None:
        x_min, x_max = min(psu_data) - (max(psu_data) - min(psu_data)) * 0.1, max(psu_data) + (max(psu_data) - min(psu_data)) * 0.1
    x_plot = np.linspace(x_min, x_max, 500)
    pdf_values = kde(x_plot)

    # Calculate percentile
    percentile = stats.percentileofscore(psu_data, new_psu_value, kind='rank')

    # Plotting
    fig, ax = plt.subplots(figsize=(10, 4))

    # Plot the filled area under the curve
    ax.fill_between(x_plot, pdf_values, color='#D5EDD2', alpha=0.8)

    # Plot the curve itself
    ax.plot(x_plot, pdf_values, color='#76BF6A', linewidth=2)

    # Add the current_x marker (person icon)
    # Find the y-value of the KDE at current_x
    current_x_pdf_value = kde(new_psu_value)[0]
    ax.plot(new_psu_value, current_x_pdf_value, marker='o', markersize=12, color='#2BBAB7', linestyle='None', zorder=5)
    ax.annotate("", xy=(new_psu_value, current_x_pdf_value), 
                xytext=(new_psu_value, current_x_pdf_value * 1.5),
                # arrowprops=dict(facecolor='#2BBAB7', edgecolor='none', shrink=0.05, width=5, headwidth=15),
                fontsize=10, ha='center')

    # Customize axes
    ax.set_yticks([])  # Remove y-axis ticks
    ax.set_yticklabels([]) # Remove y-axis labels
    ax.set_frame_on(False) # Remove the frame around the plot

    # Set x-axis labels to min and max of data
    ax.set_xticks([np.floor(min(psu_data)), np.ceil(max(psu_data))])
    ax.set_xticklabels([f'{int(np.floor(min(psu_data)))}', f'{int(np.ceil(max(psu_data)))}'], fontsize=12, color='#666666')

    # Title with percentage
    ax.text(0.5, 1.05, f"{int(100 - percentile)} % of patients have higher uncertainty",
            transform=ax.transAxes, fontsize=20, color='#666666',
            ha='center', va='bottom')
    # ax.text(0.65, 1.05, f"{int(percentile)}", transform=ax.transAxes, fontsize=28, color='#76BF6A', ha='center', va='bottom')

    plt.tight_layout()
    if save_path is not None:
        plt.savefig(save_path)
    plt.close()
    
def compute_uncertainties_for_patient(pred_filepath: str, affine: np.ndarray, save_dir: str, psu_data_path: str = None,
                                 num_models: int = 5, n_jobs: int = 1):
    """Compute and save voxel, lesion uncertainty maps and patient uncertainty value for a given patient.

    Args:
        pred_filepath (str): npz prediction file path (produced by precomputing/save_ens_pred_npz.py)
        affine (np.ndarray): affine transformation matrix from nifti file
        save_dir (str): directory to save the uncertainty maps
        num_models (int, optional): number of models in the ensemble. Defaults to 5.
        n_jobs (int, optional): number of jobs for parallel processing. Defaults to 1.
    Returns:
        None
    """
    if not os.path.exists(save_dir):
        os.makedirs(save_dir)
        
    # voxel uncertainty map
    # TODO: define the save path according to the internal project structure
    voxel_uncertainty_maps(pred_filepath=pred_filepath,
                           affine=affine,
                           save_path=os.path.join(save_dir, 'voxel_uncertainty_map.nii.gz'),
                           num_models=num_models,
                           n_jobs=n_jobs)
    
    # lesion uncertainty map
    # TODO: define the save path according to the internal project structure
    lesion_uncertainty_maps(pred_filepath=pred_filepath,
                            affine=affine,
                            save_path=os.path.join(save_dir, 'lesion_uncertainty_map.nii.gz'),
                            num_models=num_models,
                            n_jobs=n_jobs)
    
    # patient uncertainty value
    # TODO: save or user the psu_value as needed
    psu_value = patient_uncertainty_value(pred_filepath=pred_filepath,
                                          num_models=num_models)
    
    if psu_data_path is not None and psu_value is not None:
        # TODO: load the psu_data according to the internal project structure
        psu_data = pd.read_csv(os.path.join(psu_data_path, "patient_uncs_eval_all_ms.csv"), index_col=0)[["DSC-based mem_th", "set name", "hash"]]
        psu_data = psu_data[psu_data["set name"] != "ood"]["DSC-based mem_th"].values
        
        # TODO: define the save path according to the internal project structure
        plot_psu_distribution(
            psu_data=psu_data,
            new_psu_value=psu_value,
            save_path=os.path.join(save_dir, 'patient_uncertainty_value.png')
        )
        